format = """
[     ](fg:base bg:blue)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[ ](fg:green bg:base)
"""

add_newline = true

palette = "catppuccin_macchiato"

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"

[directory]
style = 'bold bg:blue fg:surface0'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:green fg:surface0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:surface0"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
symbol = " "
style = "bg:sky"
format = '[ $symbol $context ]($style)'

[time]
disabled = true
time_format = "%R"             # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'

# LANGUAGES
[python]
#style = "bg:maroon"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
